CREATE TABLE news (
 news_id BIGSERIAL PRIMARY KEY,slug VARCHAR(100) UNIQUE NOT NULL,title VARCHAR(150) NOT NULL,body TEXT NOT NULL,
 status VARCHAR(20) NOT NULL CHECK(status IN ('DRAFT','PUBLISHED','HIDDEN','ARCHIVED')),
 published_at TIMESTAMP NOT NULL,created_at TIMESTAMP NOT NULL DEFAULT LOCALTIMESTAMP,updated_at TIMESTAMP NOT NULL DEFAULT LOCALTIMESTAMP
);
CREATE INDEX idx_news_public ON news(status,published_at DESC);
