CREATE TABLE landing_pages (
 landing_page_id BIGSERIAL PRIMARY KEY,slug VARCHAR(100) UNIQUE NOT NULL,title VARCHAR(150) NOT NULL,body TEXT,
 cta_label VARCHAR(100),cta_url VARCHAR(500),status VARCHAR(20) NOT NULL CHECK(status IN ('DRAFT','PUBLISHED','HIDDEN','ARCHIVED')),
 created_at TIMESTAMP NOT NULL DEFAULT LOCALTIMESTAMP,updated_at TIMESTAMP NOT NULL DEFAULT LOCALTIMESTAMP
);
