package world.creve.playpit.repository;
import java.util.*;
import java.time.*;
import org.springframework.data.jpa.repository.*;
import org.springframework.data.domain.*;
import org.springframework.data.repository.query.Param;
import world.creve.playpit.entity.*;
import world.creve.playpit.dto.response.*;
public interface MessageRepository extends JpaRepository<Message,Long>,JpaSpecificationExecutor<Message> {
    @Query("select new world.creve.playpit.dto.response.MessageRow(m.messageId,m.creatorId,m.artworkId,m.message,m.displayName,m.anonymous,m.petalType,m.petalSeed,m.createdAt,a.title,c.name) from Message m left join Creator c on m.creatorId=c.creatorId left join Artwork a on m.artworkId=a.artworkId where m.eventId=:eventId and m.status=world.creve.playpit.entity.MessageStatus.PUBLISHED and (m.creatorId is null or c.status='PUBLISHED') and (m.artworkId is null or a.status='PUBLISHED') order by m.messageId asc") List<MessageRow> findPublishedMessagesByEventId(@Param("eventId")Long eventId,Pageable pageable);
    @Query("select new world.creve.playpit.dto.response.MessageRow(m.messageId,m.creatorId,m.artworkId,m.message,m.displayName,m.anonymous,m.petalType,m.petalSeed,m.createdAt,a.title,c.name) from Message m left join Creator c on m.creatorId=c.creatorId left join Artwork a on m.artworkId=a.artworkId where m.eventId=:eventId and m.status=world.creve.playpit.entity.MessageStatus.PUBLISHED and (m.creatorId is null or c.status='PUBLISHED') and (m.artworkId is null or a.status='PUBLISHED') and m.creatorId=:creatorId order by m.messageId asc") List<MessageRow> findPublishedMessagesByCreatorId(@Param("eventId")Long eventId,@Param("creatorId")Long creatorId,Pageable pageable);
    @Query("select new world.creve.playpit.dto.response.MessageRow(m.messageId,m.creatorId,m.artworkId,m.message,m.displayName,m.anonymous,m.petalType,m.petalSeed,m.createdAt,a.title,c.name) from Message m left join Creator c on m.creatorId=c.creatorId left join Artwork a on m.artworkId=a.artworkId where m.eventId=:eventId and m.status=world.creve.playpit.entity.MessageStatus.PUBLISHED and (m.creatorId is null or c.status='PUBLISHED') and (m.artworkId is null or a.status='PUBLISHED') and m.artworkId=:artworkId order by m.messageId asc") List<MessageRow> findPublishedMessagesByArtworkId(@Param("eventId")Long eventId,@Param("artworkId")Long artworkId,Pageable pageable);
    @Query(value="select new world.creve.playpit.dto.response.MessageRow(m.messageId,m.creatorId,m.artworkId,m.message,m.displayName,m.anonymous,m.petalType,m.petalSeed,m.createdAt,a.title,c.name) from Message m left join Creator c on m.creatorId=c.creatorId left join Artwork a on m.artworkId=a.artworkId where m.eventId=:eventId and m.status=world.creve.playpit.entity.MessageStatus.PUBLISHED and (m.creatorId is null or c.status='PUBLISHED') and (m.artworkId is null or a.status='PUBLISHED') and (:creatorId is null or m.creatorId=:creatorId) and (:artworkId is null or m.artworkId=:artworkId) order by m.messageId asc",countQuery="select count(m) from Message m left join Creator c on m.creatorId=c.creatorId left join Artwork a on m.artworkId=a.artworkId where m.eventId=:eventId and m.status=world.creve.playpit.entity.MessageStatus.PUBLISHED and (m.creatorId is null or c.status='PUBLISHED') and (m.artworkId is null or a.status='PUBLISHED') and (:creatorId is null or m.creatorId=:creatorId) and (:artworkId is null or m.artworkId=:artworkId)") Page<MessageRow> findFiltered(@Param("eventId")Long eventId,@Param("creatorId")Long creatorId,@Param("artworkId")Long artworkId,Pageable pageable);
    @Query("select count(m) from Message m left join Creator c on m.creatorId=c.creatorId left join Artwork a on m.artworkId=a.artworkId where m.eventId=:eventId and m.status=world.creve.playpit.entity.MessageStatus.PUBLISHED and (m.creatorId is null or c.status='PUBLISHED') and (m.artworkId is null or a.status='PUBLISHED')") long countPublishedMessagesByEventId(@Param("eventId")Long eventId);
    @Query("select count(m) from Message m left join Creator c on m.creatorId=c.creatorId left join Artwork a on m.artworkId=a.artworkId where m.eventId=:eventId and m.status=world.creve.playpit.entity.MessageStatus.PUBLISHED and (m.creatorId is null or c.status='PUBLISHED') and (m.artworkId is null or a.status='PUBLISHED') and (:creatorId is null or m.creatorId=:creatorId) and (:artworkId is null or m.artworkId=:artworkId)") long countVisible(@Param("eventId")Long eventId,@Param("creatorId")Long creatorId,@Param("artworkId")Long artworkId);
    @Query(value="select count(*) from message_submission_receipts where session_hash=:hash and created_at>:after",nativeQuery=true) long countRecentMessagesBySessionHash(@Param("hash")String hash,@Param("after")LocalDateTime after);
    @Query(value="select exists(select 1 from message_submission_receipts where session_hash=:hash and body_hash=:bodyHash and created_at>:after)",nativeQuery=true) boolean existsRecentDuplicateMessage(@Param("hash")String hash,@Param("bodyHash")String bodyHash,@Param("after")LocalDateTime after);
    @Query("select new world.creve.playpit.dto.response.CreatorMessageCount(c.creatorId,c.slug,c.name,count(m)) from Message m left join Creator c on m.creatorId=c.creatorId left join Artwork a on m.artworkId=a.artworkId where m.eventId=:eventId and m.status=world.creve.playpit.entity.MessageStatus.PUBLISHED and (m.creatorId is null or c.status='PUBLISHED') and (m.artworkId is null or a.status='PUBLISHED') group by c.creatorId,c.slug,c.name order by c.name") List<CreatorMessageCount> creatorCounts(@Param("eventId")Long eventId);
}
